config/routes.rb
Rails.application.routes.draw do
  resources :bookings
  root 'bookings#index'  

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :shift
  belongs_to :editor
  belongs_to :typist
  belongs_to :reader
end

app/models/editor.rb
class Editor < ActiveRecord::Base
    has_many :bookings
end

app/models/reader.rb
class Reader < ActiveRecord::Base
    has_many :bookings
end

app/models/shift.rb
class Shift < ActiveRecord::Base
    has_many :bookings
end

app/models/typist.rb
class Typist < ActiveRecord::Base
    has_many :bookings
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
    def new
        @shifts = Shift.all.map  {|s| [ s.name, s.id ] }
        @editors = Editor.all.map{|e| [ e.name, e.id ] }
        @typists = Typist.all.map{|t| [ t.name, t.id ] }
        @readers = Reader.all.map{|r| [ r.name, r.id ] }
    end
    
    def create
        @booking = Booking.new(booking_params)
          if @booking.save
             redirect_to booking_path(@booking)
          else
             render 'new'
          end
    end
    
    def show
    end
    
    def index
        #session.clear
        
        
        @years = (2016..2018).each.map {|y| [y, y]}
        months = %w(Jan Feb Mar Apr May Jun Jul Aug Sep Oct Nov Dec)
        @months = months.each.map{|m| [m, months.index(m) + 1]}
        
        @shifts = Shift.all.map  {|s| [ s.name, s.id ] }
        @editors = Editor.all.map{|e| [ e.name, e.id ] }
        @typists = Typist.all.map{|t| [ t.name, t.id ] }
        @readers = Reader.all.map{|r| [ r.name, r.id ] }
         
        
         if !params["year"] && !params["month"] && session["year"] && session["month"]
                
               redirect_to bookings_path( "year" => session["year"], "month" => session["month"], :look => params[:look]) and return
             
         
         
         elsif !params["year"] && !params["month"]
            
               redirect_to bookings_path( "year" => "2016", "month" => "1") and return             
        end
         
        
        
        @year = params["year"].to_i
        @month = params["month"].to_i
        
        s_day = Date.new(@year,@month,1)
        #s_day = Date.new(2016,1,1)
        e_day = s_day.end_of_month
        
        #@filter_hash = params[:look]
         @filter_hash = ActiveSupport::HashWithIndifferentAccess.new(params[:look])
        
        @bookings = Booking.where("date >= :start_date AND date <= :end_date",
   {start_date:  s_day, end_date:  e_day}).order( :shift_id, :date)
   
        
        
#         if @year
#           #@bookings = @bookings.where("strftime('%Y', date) + 0 = ?", @year)
#           @bookings = Booking.where("date >= :start_date AND date <= :end_date",
#   {start_date:  boy, end_date:  eoy})
#         end
        
#         if @month
#             #@bookings = @bookings.where("strftime('%m', date) + 0 = ?", @month)
          
#         end 
        
        if @filter_hash
            
              @filter_hash.each do |key, value|
                  @filter_hash.delete(key) if value == ""
              end
            @bookings = @bookings.where(@filter_hash).order(:shift_id, :date)

            
        end    
            
    session["year"] = params["year"]
    session["month"] = params["month"] 
    
    #session.clear

    end 
    

    
    def edit
        @booking = Booking.find(params[:id])
        @shifts = Shift.all.map{|s| [ s.name, s.id ] }
        @editors = Editor.all.map{|e| [ e.name, e.id ] }
        @typists = Typist.all.map{|t| [ t.name, t.id ] }
        @readers = Reader.all.map{|r| [ r.name, r.id ] }
       
    end
   
    
    def update
          @booking = Booking.find params[:id]
          @booking.update_attributes!(booking_params)
          redirect_to bookings_path
        
    end    
    
    
   private
    def booking_params
        params.require(:booking).permit(:date, :shift_id, :editor_id, :typist_id, :reader_id )
    
    end        
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :shift_id %><br>
    <%= f.text_field :shift_id %>
  </div>
  <div class="field">
    <%= f.label :editor_id %><br>
    <%= f.text_field :editor_id %>
  </div>
  <div class="field">
    <%= f.label :typist_id %><br>
    <%= f.text_field :typist_id %>
  </div>
  <div class="field">
    <%= f.label :reader_id %><br>
    <%= f.text_field :reader_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/edit.html.erb
<%= form_tag booking_path(@booking), :method => :put do %>

    <h2>Shift Details(not to be changed):</h2> 
   
    <%= date_select :booking, :date, selected: @booking.date %>
    
   
    <%= select_tag "booking[shift_id]", options_for_select(@shifts, selected: @booking.shift_id),  prompt: "Shift" %>
    <h2>Edit Officers for the Shift:</h2> 
 <table> 
   <tbody>    
      <tr>
    <td><%= label_tag "editor:"%></td>
    <td><%= select_tag "booking[editor_id]", options_for_select(@editors, selected: @booking.editor_id), prompt: "Editor" %></td>
  </tr>
  <tr>
    <td><%= label_tag "typist:"%></td>
      <td><%= select_tag "booking[typist_id]", options_for_select(@typists, selected: @booking.typist_id), prompt: "Typist" %></td>
 
 </tr>
 <tr>
    <td><%= label_tag "reader:"%></td>
      <td><%= select_tag "booking[reader_id]", options_for_select(@readers,  selected: @booking.reader_id), prompt: "Reader" %></td>
   </tr>

 <tr>
    <td><%= submit_tag "edit", :name => nil, class: "button" %></td>
  </tr>
  
<% end %>
     
   <tbody>
</table>


<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<body>

<h1>DUTY BOOKER APP</h1>



<table>
<%= form_tag bookings_path, method: 'get' do %>

  <tbody>
    <tr>
      <td><%= label_tag "year:"%></td>
      <td><%= select_tag "year", options_for_select(@years, selected: @year), prompt: "year"%></td> 
      <td><%= label_tag "month:"%>
      <td><%= select_tag "month", options_for_select(@months, selected: @month), prompt: "month" %></td>
      <td><%= submit_tag "submit period", :name => nil, class: "button" %></td>
      <% end %>
    </tr>  
  </tbody> 
</table>

<%= form_tag bookings_path, method: 'get' do %>
<table>
   <tbody>
     <tr>
  
    <td><%= select_tag "look[shift_id]", options_for_select(@shifts),  prompt: "Shift" %></td>
    <td><%= select_tag "look[editor_id]", options_for_select(@editors), prompt: "Editor" %></td>
    <td><%= select_tag "look[typist_id]", options_for_select(@typists), prompt: "Typist" %></td>
    <td><%= select_tag  "look[reader_id]", options_for_select(@readers), prompt: "Reader" %></td>
    <td><%= submit_tag "filter bookings", :name => nil, class: "button" %></td>
<% end %>
     </tr> 
   <tbody>
</table>

<table id = "bookings">
  <thead>
    <tr>
      <th >date</th>
      <th >shift</th>
      <th >editor</th>
      <th >typist</th>
      <th >reader</th>
      <th >edit_link</th>
     </tr>
  </thead>
  <tbody>
      <% @bookings.each do |b| %>
          <% editor  = b.editor ? b.editor.name : "    ----" %>
          <% typist  = b.typist ? b.typist.name : "    ----" %>
          <% reader  = b.reader ? b.reader.name : "    ----" %>
         <tr>
          <td><%= b.date %></td>
          <td><%= b.shift.name %></td>
          <td><%= editor %></td>
          <td><%= typist %></td>
          <td><%= reader %></td>
          <td><%= link_to 'change', edit_booking_path(b) %></td>
         <% end %> 
         </tr>  
  </tbody> 

</table>
</body>
      
      

app/views/bookings/new.html.erb
<h1>New Booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @booking.date %>
</p>

<p>
  <strong>Shift:</strong>
  <%= @booking.shift %>
</p>

<p>
  <strong>Editor:</strong>
  <%= @booking.editor %>
</p>

<p>
  <strong>Typist:</strong>
  <%= @booking.typist %>
</p>

<p>
  <strong>Reader:</strong>
  <%= @booking.reader %>
</p>

<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RnuApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>